"""
morning_opt_run.py — FULL OPTIONS REPLAY of the two morning champions through
REAL Polygon QQQ option 5-minute bars, over the full usable options window.

Strategies (stock legs generated by morning_opt.orb2s_trade, verified
bit-identical to morning_qqq4.orb2s):
  A. HF champion  "O4 Rn nr.7 e660": orb2s(or_bars=4, rr=None, nr=0.7,
     last_entry=660, sides='both')  — noon exit, no target.
  B. vM champion:                     orb2s(or_bars=5, rr=2.0, nr=0.3,
     last_entry=690, sides='both')

Grid per strategy: dte_bucket x strike_mode = {'0dte','1-3d','4-10d'} x
{'atm','otm1'}.  Costs: 1% of premium per side (project convention); 2%/side
sensitivity recomputed from raw bar closes for every cell.

Coverage: Polygon option minute bars are gated by a ROLLING 2-year plan
window — real bars from 2024-07-22 onward only (ARENA not coverable, GATE
missing its first week).  START below reflects that floor.

Research only — no orders anywhere.
Usage:  python morning_opt_run.py          (writes runs/morning_options_result.txt)
"""

from __future__ import annotations

import datetime as dt
import json
import sys
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

import numpy as np

from morning_opt import (DTE_BUCKETS, STRIKE_MODES, get_days, orb2s_trade,
                         replay, summarize, trade_list, vm_trade)

START = "2024-07-22"          # first trading day inside the rolling 2y plan window
GATE_END = dt.date(2025, 7, 14)   # ladder boundary: GATE / FINAL split for reporting

RUNS = Path(__file__).with_name("runs")
RUNS.mkdir(exist_ok=True)
OUT = RUNS / "morning_options_result.txt"


def hf_trade(day):
    """HF champion 'O4 Rn nr.7 e660' (morning_hf.py F1 protocol champion)."""
    return orb2s_trade(day, 4, None, nr=0.7, last_entry=660, sides="both")


STRATS = [
    ("A_HF_O4_Rn_nr.7_e660", hf_trade,
     "orb2s(or_bars=4, rr=None, nr=0.7, last_entry=660, sides='both')"),
    ("B_vM", vm_trade,
     "orb2s(or_bars=5, rr=2.0, nr=0.3, last_entry=690, sides='both')"),
]


# ------------------------------------------------------------------ helpers
def equivalence_check():
    """orb2s_trade(4, None, 0.7, 660) must reproduce morning_qqq4.orb2s exactly
    (smoke only verified the vM parameter set)."""
    import morning_qqq4
    dd = get_days()
    n_cmp = n_tr = 0
    for d in dd:
        ref = morning_qqq4.orb2s(d, 4, None, nr=0.7, last_entry=660, sides="both")
        new = hf_trade(d)
        assert (ref is None) == (new is None), f"presence mismatch {d['date']}"
        if ref is not None:
            assert abs(ref - new["stock_ret_net"]) < 1e-12, \
                f"return mismatch {d['date']}: {ref} vs {new['stock_ret_net']}"
            n_tr += 1
        n_cmp += 1
    return n_cmp, n_tr


def stock_stats(trades):
    r = np.array([t["stock_ret_net"] for t in trades], dtype=float)
    if not len(r):
        return {"n": 0, "tot": None, "avg": None, "med": None, "win": None}
    return {"n": len(r), "tot": float(r.sum()), "avg": float(r.mean()),
            "med": float(np.median(r)), "win": float((r > 0).mean())}


def resum(results, cost):
    """Re-aggregate a replay at a different per-side premium cost, recomputed
    from the RAW option bar closes (opt_entry/opt_exit)."""
    filled = [r for r in results if r["status"] == "filled"]
    if not filled:
        return {"avg": None, "med": None, "tot": None, "win": None}
    rr = np.array([(r["opt_exit"] * (1 - cost) - r["opt_entry"] * (1 + cost))
                   / (r["opt_entry"] * (1 + cost)) for r in filled], dtype=float)
    return {"avg": float(rr.mean()), "med": float(np.median(rr)),
            "tot": float(rr.sum()), "win": float((rr > 0).mean())}


def split_tot(results, cost=0.01):
    """Filled-trade option totals in the GATE-era vs FINAL-era sub-windows."""
    out = {}
    for tag, keep in (("gate_era", lambda d: d < GATE_END),
                      ("final_era", lambda d: d >= GATE_END)):
        sub = [r for r in results if r["status"] == "filled" and keep(r["date"])]
        rr = [(r["opt_exit"] * (1 - cost) - r["opt_entry"] * (1 + cost))
              / (r["opt_entry"] * (1 + cost)) for r in sub]
        out[tag] = {"n": len(sub), "tot": float(np.sum(rr)) if rr else None}
    return out


def fmt_pct(x, digits=1):
    return "None" if x is None else f"{x * 100:+.{digits}f}%"


# ------------------------------------------------------------------ main
def main():
    lines = []

    def emit(s=""):
        print(s, flush=True)
        lines.append(s)

    emit("MORNING OPTIONS REPLAY — real Polygon QQQ option 5-min bars")
    emit(f"run at {dt.datetime.now():%Y-%m-%d %H:%M}, window start {START} "
         f"(rolling 2y plan floor), end = last cached underlying day")
    emit("costs: 1%/side of premium (2%/side sensitivity recomputed per cell); "
         "stock leg carries 2bps round trip")
    emit()

    n_cmp, n_tr = equivalence_check()
    emit(f"EQUIVALENCE — orb2s_trade(4, None, nr=0.7, 660, 'both') vs "
         f"morning_qqq4.orb2s: {n_cmp} days, {n_tr} trades, all identical to 1e-12")
    emit()

    all_results = {}       # (strat, bucket, mode) -> replay results
    table = []             # summary rows for the orchestrator

    for sname, fn, desc in STRATS:
        trades = trade_list(fn, start=START)
        ss = stock_stats(trades)
        d0, d1 = trades[0]["date"], trades[-1]["date"]
        emit("=" * 100)
        emit(f"STRATEGY {sname}: {desc}")
        emit(f"  window {d0} .. {d1}  |  STOCK baseline (2bps, all {ss['n']} trades): "
             f"tot {fmt_pct(ss['tot'], 2)}  avg {ss['avg'] * 1e4:+.1f}bp  "
             f"med {ss['med'] * 1e4:+.1f}bp  win {ss['win']:.0%}")
        gate_tr = [t for t in trades if t["date"] < GATE_END]
        fin_tr = [t for t in trades if t["date"] >= GATE_END]
        emit(f"  stock by era: gate-era {fmt_pct(stock_stats(gate_tr)['tot'], 2)} "
             f"(n={len(gate_tr)}) | final-era {fmt_pct(stock_stats(fin_tr)['tot'], 2)} "
             f"(n={len(fin_tr)})")
        emit()
        hdr = (f"  {'cell':<14} {'n':>4} {'fill':>5} {'fill%':>6} | "
               f"{'win':>4} {'avg':>8} {'med':>8} {'tot':>9} | "
               f"{'avg@2%':>8} {'tot@2%':>9} | {'stock(fill)':>11}")
        emit(hdr)
        emit("  " + "-" * (len(hdr) - 2))
        for bucket in DTE_BUCKETS:
            for mode in STRIKE_MODES:
                res = replay(trades, bucket, mode)
                all_results[(sname, bucket, mode)] = res
                s = summarize(res)
                s2 = resum(res, 0.02)
                stk = stock_stats([r for r in res if r["status"] == "filled"])
                fill_rate = 1 - s["unfillable_rate"]
                win_s = "-" if s["win"] is None else f"{s['win']:.0%}"
                emit(f"  {bucket + '/' + mode:<14} {s['n']:>4} {s['filled']:>5} "
                     f"{fill_rate:>6.0%} | {win_s:>4} "
                     f"{fmt_pct(s['avg_ret']):>8} {fmt_pct(s['med_ret']):>8} "
                     f"{fmt_pct(s['tot_ret']):>9} | {fmt_pct(s2['avg']):>8} "
                     f"{fmt_pct(s2['tot']):>9} | {fmt_pct(stk['tot'], 2):>11}")
                table.append({
                    "strategy": sname, "dte": bucket, "strike": mode,
                    "n": s["n"], "filled": s["filled"],
                    "fillable_rate": round(fill_rate, 4),
                    "no_contract": s["no_contract"], "unfillable": s["unfillable"],
                    "win_rate": None if s["win"] is None else round(s["win"], 3),
                    "avg_ret_premium": None if s["avg_ret"] is None else round(s["avg_ret"], 4),
                    "med_ret_premium": None if s["med_ret"] is None else round(s["med_ret"], 4),
                    "tot_ret_premium": None if s["tot_ret"] is None else round(s["tot_ret"], 4),
                    "avg_at_2pct_side": None if s2["avg"] is None else round(s2["avg"], 4),
                    "tot_at_2pct_side": None if s2["tot"] is None else round(s2["tot"], 4),
                    "stock_tot_on_filled": None if stk["tot"] is None else round(stk["tot"], 4),
                    "era_split": split_tot(res),
                })
        emit()

    # ------------------------------------------------------------ best cell
    emit("=" * 100)
    cand = [r for r in table if r["tot_ret_premium"] is not None]
    ok80 = [r for r in cand if r["fillable_rate"] > 0.80]
    best = max(ok80 or cand, key=lambda r: r["tot_ret_premium"])
    emit(f"BEST CELL (max total premium return"
         f"{', fillable>80% only' if ok80 else ''}): "
         f"{best['strategy']} {best['dte']}/{best['strike']}")
    emit(f"  n={best['n']} filled={best['filled']} (fillable {best['fillable_rate']:.0%})  "
         f"win {best['win_rate']:.0%}  avg {fmt_pct(best['avg_ret_premium'])}  "
         f"med {fmt_pct(best['med_ret_premium'])}  tot {fmt_pct(best['tot_ret_premium'])}")
    emit(f"  2%/side sensitivity: avg {fmt_pct(best['avg_at_2pct_side'])}  "
         f"tot {fmt_pct(best['tot_at_2pct_side'])}")
    emit(f"  same trades on STOCK (2bps): tot {fmt_pct(best['stock_tot_on_filled'], 2)}")
    emit(f"  era split (1%/side): gate-era {best['era_split']['gate_era']}  "
         f"final-era {best['era_split']['final_era']}")
    emit()
    emit("COVERAGE HONESTY: options replay window is ONLY "
         f"{START}..now — GATE (minus its first week) + FINAL. That is ONE "
         "market era (post-2024); the 2022 bear / 2023 chop that formed the "
         "ARENA is NOT testable with real option bars. Unfillable and "
         "no-contract trades never enter P&L and are reported per cell above.")

    OUT.write_text("\n".join(lines) + "\n\nJSON_TABLE = " +
                   json.dumps(table, default=str, indent=1), encoding="utf-8")
    print(f"\nwrote {OUT}")
    (RUNS / "morning_options_result.json").write_text(
        json.dumps(table, default=str, indent=1), encoding="utf-8")


if __name__ == "__main__":
    main()
